environment:
  matrix:
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PYTHON%\\bin;%PATH%"
  - "SET PYTHONPATH=%PYTHONPATH%;%APPVEYOR_BUILD_FOLDER%\\app"
  - "python -m pip install -r req.windows.txt"
  - "python -m pip install -r req.test.txt"

build: off

test_script:
  - pytest --cov wots
