environment:
  matrix:
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PYTHON%\\bin;%PATH%"
  - "SET PYTHONPATH=%PYTHONPATH%;%APPVEYOR_BUILD_FOLDER%\\app"
  - "python -m pip install -r requirements.windows.txt"

build: off

test_script:
  - "%PYTHON%\\python.exe -m unittest discover -s test -t test -p test_*.py"
