image:
  - Visual Studio 2015 # Windows Server 2012 R2
  - Visual Studio 2017 # Windows Server 2016
environment:
  matrix:
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PYTHON%\\bin;%PATH%"
  - "SET PYTHONPATH=%PYTHONPATH%;%APPVEYOR_BUILD_FOLDER%\\app"
  - "SET CL=-FI"%VCINSTALLDIR%\INCLUDE\stdint.h" # pycrypto build workaround
  - "python -m pip install -r requirements.windows.txt"
  - "python -m pip install -r requirements.test.txt"

build: off

test_script:
  - pytest --cov app
after_test:
  - coveralls
  - pyinstaller wizard.spec
