image:
  - Visual Studio 2015
environment:
  matrix:
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"

install:
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PYTHON%\\bin;%PATH%
  - SET PYTHONPATH=%PYTHONPATH%;%APPVEYOR_BUILD_FOLDER%\\app
  - SET CL=-FI"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\stdint.h" # pycrypto build workaround
  - python -m pip install -r requirements.windows.txt
  - python -m pip install -r requirements.test.txt

build: off

test_script:
  - pytest --cov app
  - coveralls
  - pyinstaller wizard.spec
