os:
  - linux
language: python
python:
  - 3.6
install:
  - pip install -r req.main.txt
  - pip install -r req.test.txt
before_script:
  - export PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/app
script:
  - pytest --cov wots
