pool:
  vmImage: 'macOS-10.13'
strategy:
  matrix:
    Python36:
      python.version: '3.6'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      python -m pip install -r requirements.txt
      python -m pip install -r requirements.test.txt
    displayName: 'Install dependencies'

  - script: make test
    displayName: 'Run tests'

  - script: |
      echo 'repo_token: $(COVERALLS_REPO_TOKEN)' > .coveralls.yml
      coveralls
    displayName: 'Report coverage'

  - script: make build
    displayName: 'Build executable'
