import tools.dict

_SET_ABBREVIATIONS_SOURCE = {
    '10E': ('Tenth Edition', '10th Edition',),
    '2ED': ('Unlimited Edition', '2E', 'Unlimited',),
    '3ED': ('Revised Edition', '3E', 'Revised',),
    '4ED': ('Fourth Edition', '4th Edition', '4E',),
    '5DN': ('Fifth Dawn', 'FD',),
    '5ED': ('Fifth Edition', '5th Edition', '5E',),
    '6ED': ('Sixth Edition', '6th Edition', '6E', 'Classic Sixth Edition',),
    '7ED': ('Seventh Edition', '7th Edition', '7E',),
    '8ED': ('Eighth Edition', '8th Edition', '8E',),
    '9ED': ('Ninth Edition', '9th Edition', '9E',),
    'ALA': ('Shards of Alara', 'SA',),
    'ALL': ('Alliances', 'AL',),
    'APC': ('Apocalypse', 'AP',),
    'ARB': ('Alara Reborn', 'AR',),
    'ARC': ('Archenemy',),
    'ARL': ('Arena League', 'Arena',),
    'ARN': ('Arabian Nights',),
    'ATH': ('Anthologies',),
    'ATQ': ('Antiquities',),
    'AVR': ('Avacyn Restored',),
    'BFZ': ('Battle for Zendikar',),
    'BNG': ('Born of the Gods',),
    'BOK': ('Betrayers of Kamigawa', 'BK',),
    'BRB': ('Battle Royale Box Set', 'Battle Royal',),
    'BTD': ('Beatdown Box Set',),
    'C13': ('Commander 2013', 'Commander 2013 Edition', 'Commander2013',),
    'C14': ('Commander 2014', 'Commander 2014 Edition', 'Commander2014',),
    'CHK': ('Champions of Kamigawa', 'CK',),
    'CHR': ('Chronicles',),
    'CM1': ("Commander's Arsenal", 'CMA',),
    'CMD': ('Commander',),
    'CNS': ('Conspiracy',),
    'CON': ('Conflux', 'CF', 'CFX',),
    'CSP': ('Coldsnap', 'CS',),
    'CTD': ('Coldsnap Theme Decks', 'Coldsnap Reprints',),
    'DD2': ('Duel Decks: Jace vs. Chandra', 'Jace vs. Chandra',),
    'DDC': ('Duel Decks: Divine vs. Demonic', 'Divine vs. Demonic',),
    'DDD': ('Duel Decks: Garruk vs. Liliana', 'Garruk vs. Liliana', 'GVL', 'GVL2',),
    'DDE': ('Duel Decks: Phyrexia vs. the Coalition', 'Phyrexia vs. the Coalition',),
    'DDF': ('Duel Decks: Elspeth vs. Tezzeret', 'Elspeth vs. Tezzeret',),
    'DDG': ('Duel Decks: Knights vs. Dragons', 'Knights vs. Dragons',),
    'DDH': ('Duel Decks: Ajani vs. Nicol Bolas', 'Ajani vs. Nicol Bolas',),
    'DDI': ('Duel Decks: Venser vs. Koth', 'Venser vs. Koth',),
    'DDJ': ('Duel Decks: Izzet vs. Golgari', 'Izzet vs. Golgari',),
    'DDK': ('Duel Decks: Sorin vs. Tibalt', 'Sorin vs. Tibalt',),
    'DDL': ('Duel Decks: Heroes vs. Monsters', 'Heroes vs. Monsters',),
    'DDM': ('Duel Decks: Jace vs. Vraska', 'Jace vs. Vraska',),
    'DDN': ('Duel Decks: Speed vs. Cunning', 'Speed vs. Cunning',),
    'DDO': ('Duel Decks: Elspeth vs. Kiora', 'Elspeth vs. Kiora',),
    'DGM': ("Dragon's Maze",),
    'DIS': ('Dissension', 'DI',),
    'DKA': ('Dark Ascension',),
    'DKM': ('Deckmasters',),
    'DPA': ('Duels of the Planeswalkers',),
    'DRB': ('From the Vault: Dragons',),
    'DRK': ('The Dark', 'DK',),
    'DST': ('Darksteel', 'DS',),
    'DTK': ('Dragons of Tarkir',),
    'EVE': ('Eventide', 'ET',),
    'EVG': ('Duel Decks: Elves vs. Goblins', 'EVG2', 'Elves vs. Goblins'),
    'EXO': ('Exodus', 'EX',),
    'FEM': ('Fallen Empires', 'FE',),
    'FNM': ('Friday Night Magic', 'Friday Night Magic (FNM)',),
    'FRF': ('Fate Reforged',),
    'FUT': ('Future Sight', 'FS',),
    'GPT': ('Guildpact', 'GP',),
    'GTC': ('Gatecrash',),
    'H09': ('Premium Deck Series: Slivers',),
    'HML': ('Homelands', 'HL',),
    'HOP': ('Planechase',),
    'ICE': ('Ice Age', 'IA',),
    'INV': ('Invasion', 'IN',),
    'ISD': ('Innistrad',),
    'JOU': ('Journey into Nyx',),
    'JRW': ('Judge Rewards',),
    'JUD': ('Judgment', 'JU',),
    'KTK': ('Khans of Tarkir',),
    'LEA': ('Limited Edition Alpha', 'Alpha',),
    'LEB': ('Limited Edition Beta', 'Beta',),
    'LEG': ('Legends',),
    'LGN': ('Legions',),
    'LRW': ('Lorwyn', 'LW',),
    'M10': ('Magic 2010', '2010 Core Set',),
    'M11': ('Magic 2011', '2011 Core Set',),
    'M12': ('Magic 2012', '2012 Core Set',),
    'M13': ('Magic 2013', '2013 Core Set',),
    'M14': ('Magic 2014', '2014 Core Set',),
    'M15': ('Magic 2015', '2015 Core Set',),
    'MBP': ('Media Inserts',),
    'MBS': ('Mirrodin Besieged',),
    'MD1': ('Modern Event Deck',),
    'MGD': ('Magic Game Day Cards', 'Game Day',),
    'MIR': ('Mirage',),
    'MLP': ('Magic: The Gathering Launch Parties',),
    'MMA': ('Modern Masters',),
    'MMQ': ('Mercadian Masques', 'MM',),
    'MOR': ('Morningtide', 'MT',),
    'MPR': ('Magic Player Rewards', 'Reward cards',),
    'MRD': ('Mirrodin',),
    'NEM': ('Nemesis', 'NE',),
    'NPH': ('New Phyrexia',),
    'ODY': ('Odyssey', 'OD',),
    'ONS': ('Onslaught', 'ON',),
    'ORI': ('Magic Origins',),
    'OVS': ('Oversized Cards',),
    'PC2': ('Planechase 2012', 'Planechase 2012 Edition',),
    'PCY': ('Prophecy', 'PY', 'PR',),
    'PD2': ('Premium Deck Series: Fire and Lightning',),
    'PD3': ('Premium Deck Series: Graveborn',),
    'PLC': ('Planar Chaos', 'PC', 'PCH',),
    'PLS': ('Planeshift', 'PS',),
    'PO2': ('Portal: Second Age', 'Portal Second Age',),
    'POR': ('Portal',),
    'PRC': ('Prerelease & Release Cards',),
    'PTK': ('Portal: Three Kingdoms', 'Portal Three Kingdoms',),
    'RAV': ('Ravnica: City of Guilds', 'Ravnica', 'RA',),
    'ROE': ('Rise of the Eldrazi',),
    'RTR': ('Return to Ravnica', 'Retun to Ravnica',),
    'S99': ('Starter 1999', 'Starter', ),
    'SCG': ('Scourge', 'SC',),
    'SHM': ('Shadowmoor', 'SM',),
    'SOK': ('Saviors of Kamigawa', 'SK',),
    'SOM': ('Scars of Mirrodin',),
    'STH': ('Stronghold', 'SH',),
    'THS': ('Theros',),
    'TMP': ('Tempest', 'TE',),
    'TOR': ('Torment', 'TO', 'TR',),
    'TSP': ('Time Spiral', 'TS',),
    'TST': ('Time Spiral Timeshifted', 'TSTS'),
    'UDS': ("Urza's Destiny", 'UD',),
    'ULG': ("Urza's Legacy", 'UL',),
    'UGL': ('Unglued',),
    'UNH': ('Unhinged', 'UH',),
    'USG': ("Urza's Saga", 'US',),
    'V09': ('From the Vault: Exiled',),
    'V10': ('From the Vault: Relics',),
    'V11': ('From the Vault: Legends', 'FVL',),
    'V12': ('From the Vault: Realms',),
    'V13': ('From the Vault: Twenty',),
    'V14': ('From the Vault: Annihilation',),
    'V15': ('From the Vault: Angels',),
    'VIS': ('Visions', 'VI',),
    'WMC': ('World Magic Cup Qualifiers',),
    'WPN': ('WPN\\Gateway', 'WPN/Gateway',),
    'WTH': ('Weatherlight', 'WL',),
    'WWK': ('Worldwake',),
    'ZEN': ('Zendikar',),
}

_SETS = tools.dict.expandMapping(_SET_ABBREVIATIONS_SOURCE)


def getAbbreviation(setNameString):
    return _SETS[setNameString]


def getFullName(setAbbrv):
    return _SET_ABBREVIATIONS_SOURCE[setAbbrv][0]
